development:
  prod:
    client_id: <%= ENV['PRODUCTION_CLIENT_ID'] %>
    client_secret: <%= ENV['PRODUCTION_CLIENT_SECRET'] %>
    enabled: <%= ENV['PRODUCTION_ENABLED'] %>
    environment: <%= ENV['PRODUCTION_ENVIRONMENT'] %>
  dev:
    client_id: <%= ENV['DEVELOPMENT_CLIENT_ID'] %>
    client_secret: <%= ENV['DEVELOPMENT_CLIENT_SECRET'] %>
    enabled: <%= ENV['DEVELOPMENT_ENABLED'] %>
    environment: <%= ENV['DEVELOPMENT_ENVIRONMENT'] %>

test:
  prod:
    client_id: <%= ENV['PRODUCTION_CLIENT_ID'] %>
    client_secret: <%= ENV['PRODUCTION_CLIENT_SECRET'] %>
    enabled: <%= ENV['PRODUCTION_ENABLED'] %>
    environment: <%= ENV['PRODUCTION_ENVIRONMENT'] %>
  dev:
    client_id: <%= ENV['DEVELOPMENT_CLIENT_ID'] %>
    client_secret: <%= ENV['DEVELOPMENT_CLIENT_SECRET'] %>
    enabled: <%= ENV['DEVELOPMENT_ENABLED'] %>
    environment: <%= ENV['DEVELOPMENT_ENVIRONMENT'] %>

production:
  prod:
    client_id: <%= ENV['PRODUCTION_CLIENT_ID'] %>
    client_secret: <%= ENV['PRODUCTION_CLIENT_SECRET'] %>
    enabled: <%= ENV['PRODUCTION_ENABLED'] %>
    environment: <%= ENV['PRODUCTION_ENVIRONMENT'] %>
  dev:
    client_id: <%= ENV['DEVELOPMENT_CLIENT_ID'] %>
    client_secret: <%= ENV['DEVELOPMENT_CLIENT_SECRET'] %>
    enabled: <%= ENV['DEVELOPMENT_ENABLED'] %>
    environment: <%= ENV['DEVELOPMENT_ENVIRONMENT'] %>
